[project]
name = "custom_utils"
version = "0.1.0"
description = "Shared custom utilities"
dependencies = [# Add lightweight shared dependencies here if needed (e.g. "numpy")
    "matplotlib",
    "numpy",
    "opencv-python",
    "pillow",
    "pyyaml",
    "scipy",
    "tqdm",
]

[tool.setuptools.packages.find]
include = ["custom_utils*"]